name: Build & deploy
on:
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: ./gradlew clean build
      - run: echo "Build Complete"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/build/libs