name: Build & deploy
on: [push]
jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ./gradlew clean build
      - run: echo "Build Complete"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/build/libs
      - run: echo "🍏 This job's status is ${{ job.status }}."