name: Build & deploy
on: [push]
jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ./gradlew clean build
      - run: echo "Build Complete"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/build/libs
      - name: copy jav via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          source: "${{ github.workspace }}/build/libs/bot-0.0.1-SNAPSHOT.jar"
          target: "bot"
          rm: true
      - name: Run bot with ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          script: killall java & java -jar bot/github/workspace/build/libs/bot-0.0.1-SNAPSHOT.jar &